### ISSUE TITLE
Database exception using Postgres 11

### ISSUE THREAD

**Issue by bartroelands** [putyourlightson/craft-campaign#117]
### Describe the bug
Downloaded and installed plugin as described, create mailing list type and campaign type. Next created a test campaign. Error occurred when trying to edit newly created campaign. Enabled GeoIP but issue remains. Also getting same error when opening Reports -> Contacts 

### To reproduce
see above

### Screenshots

Database Exception – yii\db\Exception

SQLSTATE[42703]: Undefined column: 7 ERROR: column "geoip" does not exist
LINE 1: SELECT "country", MAX(geoIp) AS "geoIp", COUNT(*) AS "count"
^
HINT: Perhaps you meant to reference the column "contacts.geoIp".
The SQL being executed was: SELECT "country", MAX(geoIp) AS "geoIp", COUNT(*) AS "count"
FROM "campaign_contacts_campaigns" "t"
INNER JOIN "campaign_contacts" "contacts" ON "contacts"."id" = "t"."contactId"
WHERE ("campaignId"=1406) AND (NOT ("opened" IS NULL))
GROUP BY "country"
Error Info: Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column "geoip" does not exist
LINE 1: SELECT "country", MAX(geoIp) AS "geoIp", COUNT(*) AS "count"
                              ^
HINT:  Perhaps you meant to reference the column "contacts.geoIp".
)
↵
Caused by: PDOException
SQLSTATE[42703]: Undefined column: 7 ERROR: column "geoip" does not exist
LINE 1: SELECT "country", MAX(geoIp) AS "geoIp", COUNT(*) AS "count"
^
HINT: Perhaps you meant to reference the column "contacts.geoIp".
in /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php at line 1290

### Versions
- Plugin version: latest fresh download today
- Craft version: Craft Pro 3.4.10.1

**Comment by bartroelands** [comment]
Checked the table on my local dev machine, the column geoIp does exists. Have same issue on staging server running in GCP using Postgres 11 db

**Comment by bartroelands** [comment]
Hello, found other issue editing a newly created mailinglist 

Database Exception – yii\db\Exception
SQLSTATE[42703]: Undefined column: 7 ERROR: column campaign_sendouts.mailinglistids does not exist
LINE 7: ..."."sendoutType" IN ($1, $2)) AND (FIND_IN_SET($3, campaign_s...
^
HINT: Perhaps you meant to reference the column "campaign_sendouts.mailingListIds".
The SQL being executed was: SELECT "elements"."id", "elements"."fieldLayoutId", "elements"."uid", "elements"."enabled", "elements"."archived", "elements"."dateCreated", "elements"."dateUpdated", "elements_sites"."slug", "elements_sites"."siteId", "elements_sites"."uri", "elements_sites"."enabled" AS "enabledForSite", "campaign_sendouts"."sid", "campaign_sendouts"."campaignId", "campaign_sendouts"."senderId", "campaign_sendouts"."sendoutType", "campaign_sendouts"."sendStatus", "campaign_sendouts"."fromName", "campaign_sendouts"."fromEmail", "campaign_sendouts"."replyToEmail", "campaign_sendouts"."subject", "campaign_sendouts"."notificationEmailAddress", "campaign_sendouts"."mailingListIds", "campaign_sendouts"."excludedMailingListIds", "campaign_sendouts"."segmentIds", "campaign_sendouts"."recipients", "campaign_sendouts"."fails", "campaign_sendouts"."schedule", "campaign_sendouts"."htmlBody", "campaign_sendouts"."plaintextBody", "campaign_sendouts"."sendDate", "campaign_sendouts"."lastSent", "content"."id" AS "contentId", "content"."title", "content"."field_addressline1", "content"."field_addressline2", "content"."field_caption", "content"."field_clientPageCallForActionButtonLink", "content"."field_clientPageCallForActionButtonText", "content"."field_clientPageCallForActionTitle", "content"."field_clientPageCareerCounselingExtraLinksTitle", "content"."field_clientPageCareerCounselingLinks", "content"."field_clientPageCareerCounselingText", "content"."field_clientPageCareerCounselingTitle", "content"."field_clientPageExtraLinks", "content"."field_clientPageHelpExtraLinksTitle", "content"."field_clientPageHelpIntro", "content"."field_clientPageHelpTitle", "content"."field_clientPageHonorariumIntro", "content"."field_clientPageHonorariumTarifs", "content"."field_clientPageHonorariumTarifsTitle", "content"."field_clientPageHonorariumTitle", "content"."field_text", "content"."field_email", "content"."field_homepageBannerMainTitle", "content"."field_homepageBannerSmallTitle", "content"."field_homepageButtonText", "content"."field_homepageClientButtonText", "content"."field_homepageClientCaption", "content"."field_homepageClientLink", "content"."field_homepageCoachingButtonText", "content"."field_homepageCoachingCaption", "content"."field_homepageCoachingLink", "content"."field_homepageLongIntroduction", "content"."field_homepageProfessionalButtonText", "content"."field_homepageProfessionalCaption", "content"."field_homepageProfessionalLink", "content"."field_homepageShortIntroduction", "content"."field_moduleDisplayName", "content"."field_moduleDisplayPublic", "content"."field_moduleDisplaySummary", "content"."field_newsPageArticle", "content"."field_newsPageIntro", "content"."field_newsPageTitle", "content"."field_pageCopy", "content"."field_partnerName", "content"."field_partnerUrl", "content"."field_psychologistPageKmoLinks", "content"."field_psychologistPageKmoTitle", "content"."field_psychologistPageCertifiedText", "content"."field_psychologistPageCertifiedTitle", "content"."field_psychologistPageCertifiedWarningText", "content"."field_psychologistPageCoursesTitle", "content"."field_psychologistPageExtraLinks", "content"."field_psychologistPageExtraLinksTitle", "content"."field_psychologistPageRoomText", "content"."field_psychologistPageRoomTitle", "content"."field_psychologistPageSupportIntro", "content"."field_psychologistPageSupportTitle", "content"."field_psychologistPageTrainingIntro", "content"."field_psychologistPageTrainingTitle", "content"."field_questionAbout", "content"."field_referencePersonNameFunction", "content"."field_referenceQuote", "content"."field_sectionIntro", "content"."field_sectionLinks", "content"."field_sectionTitle", "content"."field_shortIntro", "content"."field_teamPageVat", "content"."field_teamPageVisum", "content"."field_teamPageAddress", "content"."field_teamPageAppointment", "content"."field_teamPageCertification", "content"."field_teamPageEmail", "content"."field_teamPageExperience", "content"."field_teamPageIntro", "content"."field_teamPageMembership", "content"."field_teamPageName", "content"."field_teamPageProfessionalLinks", "content"."field_teamPageSpecialities", "content"."field_teamPageSummary", "content"."field_teamPageTelephone", "content"."field_teamPageTraining", "content"."field_teamPageWorkApproach", "content"."field_telephone", "content"."field_trainingPageContentBody", "content"."field_trainingPageDates", "content"."field_trainingPageIntro", "content"."field_trainingPagePrice", "content"."field_trainingPageSubscribeButtonLink", "content"."field_trainingPageSubscribeButtonText", "content"."field_trainingPageSubtitle", "content"."field_trainingPageTitle", "content"."field_trainingPageType"
FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS "elementsSitesId", "content"."id" AS "contentId"
FROM "elements" "elements"
INNER JOIN "campaign_sendouts" "campaign_sendouts" ON "campaign_sendouts"."id" = "elements"."id"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id"
INNER JOIN "content" "content" ON "content"."elementId" = "elements"."id"
WHERE ("campaign_sendouts"."sendoutType" IN ('regular', 'scheduled')) AND (FIND_IN_SET(1407, campaign_sendouts.mailingListIds)) AND ("elements"."archived"=FALSE) AND ("elements"."enabled"=TRUE) AND ("elements"."dateDeleted" IS NULL) AND ("elements_sites"."enabled"=TRUE) AND ("elements"."draftId" IS NULL) AND ("elements"."revisionId" IS NULL)
ORDER BY "sendDate") "subquery"
INNER JOIN "campaign_sendouts" "campaign_sendouts" ON "campaign_sendouts"."id" = "subquery"."elementsId"
INNER JOIN "elements" "elements" ON "elements"."id" = "subquery"."elementsId"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."id" = "subquery"."elementsSitesId"
INNER JOIN "content" "content" ON "content"."id" = "subquery"."contentId"
ORDER BY "sendDate"
Error Info: Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column campaign_sendouts.mailinglistids does not exist
LINE 7: ..."."sendoutType" IN ($1, $2)) AND (FIND_IN_SET($3, campaign_s...
                                                             ^
HINT:  Perhaps you meant to reference the column "campaign_sendouts.mailingListIds".
)
↵
Caused by: PDOException
SQLSTATE[42703]: Undefined column: 7 ERROR: column campaign_sendouts.mailinglistids does not exist
LINE 7: ..."."sendoutType" IN ($1, $2)) AND (FIND_IN_SET($3, campaign_s...
^
HINT: Perhaps you meant to reference the column "campaign_sendouts.mailingListIds".
in /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php at line 1290

**Comment by bencroker** [comment]
Thanks for the bug report. Can you test the develop branch locally to see if https://github.com/putyourlightson/craft-campaign/commit/ae27d11897faf3c58d939ac2f9188124ca9b29a1 fixes it?

```
composer require putyourlightson/craft-campaign:dev-develop
```

**Comment by bartroelands** [comment]
Hi,

Thanks for the quick response. Installed and tested the dev branch. The
first issue I reported is solved: can acces the campaign detail and the
report -> contacts.

The second issue I reported when going in the mailing list detail still
occurs :

Database Exception – yii\db\Exception
<http://www.yiiframework.com/doc-2.0/yii-db-exception.html>SQLSTATE[42883]:
Undefined function: 7 ERROR: function find_in_set(unknown, text) does not
exist
LINE 7: ...ampaign_sendouts"."sendoutType" IN ($1, $2)) AND (FIND_IN_SE...
^
HINT: No function matches the given name and argument types. You might need
to add explicit type casts.
The SQL being executed was: SELECT "elements"."id",
"elements"."fieldLayoutId", "elements"."uid", "elements"."enabled",
"elements"."archived", "elements"."dateCreated", "elements"."dateUpdated",
"elements_sites"."slug", "elements_sites"."siteId", "elements_sites"."uri",
"elements_sites"."enabled" AS "enabledForSite", "campaign_sendouts"."sid",
"campaign_sendouts"."campaignId", "campaign_sendouts"."senderId",
"campaign_sendouts"."sendoutType", "campaign_sendouts"."sendStatus",
"campaign_sendouts"."fromName", "campaign_sendouts"."fromEmail",
"campaign_sendouts"."replyToEmail", "campaign_sendouts"."subject",
"campaign_sendouts"."notificationEmailAddress",
"campaign_sendouts"."mailingListIds",
"campaign_sendouts"."excludedMailingListIds",
"campaign_sendouts"."segmentIds", "campaign_sendouts"."recipients",
"campaign_sendouts"."fails", "campaign_sendouts"."schedule",
"campaign_sendouts"."htmlBody", "campaign_sendouts"."plaintextBody",
"campaign_sendouts"."sendDate", "campaign_sendouts"."lastSent",
"content"."id" AS "contentId", "content"."title",
"content"."field_addressline1", "content"."field_addressline2",
"content"."field_caption",
"content"."field_clientPageCallForActionButtonLink",
"content"."field_clientPageCallForActionButtonText",
"content"."field_clientPageCallForActionTitle",
"content"."field_clientPageCareerCounselingExtraLinksTitle",
"content"."field_clientPageCareerCounselingLinks",
"content"."field_clientPageCareerCounselingText",
"content"."field_clientPageCareerCounselingTitle",
"content"."field_clientPageExtraLinks",
"content"."field_clientPageHelpExtraLinksTitle",
"content"."field_clientPageHelpIntro",
"content"."field_clientPageHelpTitle",
"content"."field_clientPageHonorariumIntro",
"content"."field_clientPageHonorariumTarifs",
"content"."field_clientPageHonorariumTarifsTitle",
"content"."field_clientPageHonorariumTitle", "content"."field_text",
"content"."field_email", "content"."field_homepageBannerMainTitle",
"content"."field_homepageBannerSmallTitle",
"content"."field_homepageButtonText",
"content"."field_homepageClientButtonText",
"content"."field_homepageClientCaption",
"content"."field_homepageClientLink",
"content"."field_homepageCoachingButtonText",
"content"."field_homepageCoachingCaption",
"content"."field_homepageCoachingLink",
"content"."field_homepageLongIntroduction",
"content"."field_homepageProfessionalButtonText",
"content"."field_homepageProfessionalCaption",
"content"."field_homepageProfessionalLink",
"content"."field_homepageShortIntroduction",
"content"."field_moduleDisplayName", "content"."field_moduleDisplayPublic",
"content"."field_moduleDisplaySummary", "content"."field_newsPageArticle",
"content"."field_newsPageIntro", "content"."field_newsPageTitle",
"content"."field_pageCopy", "content"."field_partnerName",
"content"."field_partnerUrl", "content"."field_psychologistPageKmoLinks",
"content"."field_psychologistPageKmoTitle",
"content"."field_psychologistPageCertifiedText",
"content"."field_psychologistPageCertifiedTitle",
"content"."field_psychologistPageCertifiedWarningText",
"content"."field_psychologistPageCoursesTitle",
"content"."field_psychologistPageExtraLinks",
"content"."field_psychologistPageExtraLinksTitle",
"content"."field_psychologistPageRoomText",
"content"."field_psychologistPageRoomTitle",
"content"."field_psychologistPageSupportIntro",
"content"."field_psychologistPageSupportTitle",
"content"."field_psychologistPageTrainingIntro",
"content"."field_psychologistPageTrainingTitle",
"content"."field_questionAbout",
"content"."field_referencePersonNameFunction",
"content"."field_referenceQuote", "content"."field_sectionIntro",
"content"."field_sectionLinks", "content"."field_sectionTitle",
"content"."field_shortIntro", "content"."field_teamPageVat",
"content"."field_teamPageVisum", "content"."field_teamPageAddress",
"content"."field_teamPageAppointment",
"content"."field_teamPageCertification", "content"."field_teamPageEmail",
"content"."field_teamPageExperience", "content"."field_teamPageIntro",
"content"."field_teamPageMembership", "content"."field_teamPageName",
"content"."field_teamPageProfessionalLinks",
"content"."field_teamPageSpecialities", "content"."field_teamPageSummary",
"content"."field_teamPageTelephone", "content"."field_teamPageTraining",
"content"."field_teamPageWorkApproach", "content"."field_telephone",
"content"."field_trainingPageContentBody",
"content"."field_trainingPageDates", "content"."field_trainingPageIntro",
"content"."field_trainingPagePrice",
"content"."field_trainingPageSubscribeButtonLink",
"content"."field_trainingPageSubscribeButtonText",
"content"."field_trainingPageSubtitle",
"content"."field_trainingPageTitle", "content"."field_trainingPageType"
FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS
"elementsSitesId", "content"."id" AS "contentId"
FROM "elements" "elements"
INNER JOIN "campaign_sendouts" "campaign_sendouts" ON
"campaign_sendouts"."id" = "elements"."id"
INNER JOIN "elements_sites" "elements_sites" ON
"elements_sites"."elementId" = "elements"."id"
INNER JOIN "content" "content" ON "content"."elementId" = "elements"."id"
WHERE ("campaign_sendouts"."sendoutType" IN ('regular', 'scheduled')) AND
(FIND_IN_SET(1407, "campaign_sendouts"."mailingListIds")) AND
("elements"."archived"=FALSE) AND ("elements"."enabled"=TRUE) AND
("elements"."dateDeleted" IS NULL) AND ("elements_sites"."enabled"=TRUE)
AND ("elements"."draftId" IS NULL) AND ("elements"."revisionId" IS NULL)
ORDER BY "sendDate") "subquery"
INNER JOIN "campaign_sendouts" "campaign_sendouts" ON
"campaign_sendouts"."id" = "subquery"."elementsId"
INNER JOIN "elements" "elements" ON "elements"."id" =
"subquery"."elementsId"
INNER JOIN "elements_sites" "elements_sites" ON "elements_sites"."id" =
"subquery"."elementsSitesId"
INNER JOIN "content" "content" ON "content"."id" = "subquery"."contentId"
ORDER BY "sendDate"

Error Info: Array
(
    [0] => 42883
    [1] => 7
    [2] => ERROR:  function find_in_set(unknown, text) does not
existLINE 7: ...ampaign_sendouts"."sendoutType" IN ($1, $2)) AND
(FIND_IN_SE...
                                                             ^
HINT:  No function matches the given name and argument types. You
might need to add explicit type casts.
)

↵Caused by: PDOExceptionSQLSTATE[42883]: Undefined function: 7 ERROR:
function find_in_set(unknown, text) does not exist
LINE 7: ...ampaign_sendouts"."sendoutType" IN ($1, $2)) AND (FIND_IN_SE...
^
HINT: No function matches the given name and argument types. You might need
to add explicit type casts.

in
/Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php
at
line 1290

**Comment by bencroker** [comment]
Ok, will do some further testing and post a fix soon.

**Comment by bencroker** [comment]
Please try again https://github.com/putyourlightson/craft-campaign/commit/0d52d4c9d01ce06fb0378db371545f6ffd2b89d2

**Comment by bartroelands** [comment]
Hi Ben,

This fix seems to work. No database errors anymore. I'll set up a full
end-to-end test on my local dev and staging server tonight. Will let
you know how it goes.

Thanks for the quick feedback

Bart

**Comment by bencroker** [comment]
Great, once you confirm I'll tag a release with the fixes.

**Comment by bartroelands** [comment]
Hi,

Got a new error (not sure it is postgres related though). I created a
campaign type newsletter and a mailinglist type clients. Next I created a
mailinglist 'clients'  of mailinglist type clients. Next I tried to setup
contacts. I manually created one ->OK. When I tried to import users from an
existing Craft user group, I got following error:

PHP Warning – yii\base\ErrorException
<http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html>Invalid
argument supplied for foreach()

   - 1. in
   /Users/Bart/Development/psychologennet-portal-1.0/vendor/putyourlightson/craft-campaign/src/controllers/ImportsController.phpat
   line 225

           $mailingListId = $request->getBodyParam('mailingListId');
           $import->mailingListId = $mailingListId[0] ?? '';

           // Get email and custom field indexes
           $import->emailFieldIndex = $request->getBodyParam('emailFieldIndex');
           $import->fieldIndexes = $request->getBodyParam('fieldIndexes');

           // Prepend `field_` to each custom field index
           foreach ($import->fieldIndexes as $key => $fieldIndex) {
               $import->fieldIndexes[$key] =
'field_'.$import->fieldIndexes[$key];
           }

           // Save it
           if (!Campaign::$plugin->imports->saveImport($import)) {
               Craft::$app->getSession()->setError(Craft::t('campaign',
'Couldn’t import user group.'));

               // Send the import back to the fields template
               return $this->_returnFieldsTemplate($import);

   - 2. in
   /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/ErrorHandler.php
    at line 74– yii\base\ErrorHandler::handleError
   <http://www.yiiframework.com/doc-2.0/yii-base-errorhandler.html#handleError()-detail>
   (2, 'Invalid argument supplied for fo...',
   '/Users/Bart/Development/psycholo...', 225)

       {
           // Because: https://bugs.php.net/bug.php?id=74980
           if (PHP_VERSION_ID >= 70100 && strpos($message, 'Narrowing
occurred during type inference. Please file a bug report') !== false)
{
               return null;
           }

           return parent::handleError($code, $message, $file, $line);
       }

       /**
        * @inheritdoc
        */
       public function getExceptionName($exception)

   - 3. in
   /Users/Bart/Development/psychologennet-portal-1.0/vendor/putyourlightson/craft-campaign/src/controllers/ImportsController.php
    at line 225– craft\web\ErrorHandler::handleError(2, 'Invalid argument
   supplied for fo...', '/Users/Bart/Development/psycholo...', 225, ...)

**Comment by bencroker** [comment]
Am I correct in thinking that your user group has no custom fields?

**Comment by bencroker** [comment]
If so then https://github.com/putyourlightson/craft-campaign/commit/09f3cd4b07287338c9e414862ec987492233e985 should fix it.

**Comment by bartroelands** [comment]
That is correct

Users nor user groups have custom fields

**Comment by bartroelands** [comment]
Now I get a integrity constraint error:

Integrity constraint violation – yii\db\IntegrityException
<http://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html>SQLSTATE[23502]:
Not null violation: 7 ERROR: null value in column "id" violates not-null
constraint
DETAIL: Failing row contains (null, null, null, 2, 1, 1409, email, [], 0,
0, 0, null, 2020-03-19 18:50:36, 2020-03-19 18:50:36,
6c970093-6a8e-4abf-99b9-7965d2679c30).
The SQL being executed was: INSERT INTO "campaign_imports" ("id",
"fileName", "filePath", "userGroupId", "userId", "emailFieldIndex",
"fieldIndexes", "mailingListId", "added", "updated", "fails",
"dateImported", "dateCreated", "dateUpdated", "uid") VALUES (NULL, NULL,
NULL, 2, 1, 'email', '[]', 1409, 0, 0, 0, NULL, '2020-03-19 18:50:36',
'2020-03-19 18:50:36', '6c970093-6a8e-4abf-99b9-7965d2679c30') RETURNING
"id"

Error Info: Array
(
    [0] => 23502
    [1] => 7
    [2] => ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, null, null, 2, 1, 1409, email,
[], 0, 0, 0, null, 2020-03-19 18:50:36, 2020-03-19 18:50:36,
6c970093-6a8e-4abf-99b9-7965d2679c30).
)

↵Caused by: PDOExceptionSQLSTATE[23502]: Not null violation: 7 ERROR: null
value in column "id" violates not-null constraint
DETAIL: Failing row contains (null, null, null, 2, 1, 1409, email, [], 0,
0, 0, null, 2020-03-19 18:50:36, 2020-03-19 18:50:36,
6c970093-6a8e-4abf-99b9-7965d2679c30).

in
/Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php
at
line 1290

**Comment by bencroker** [comment]
Ok I'll replicate this locally and do some further testing.

**Comment by bartroelands** [comment]
Ok thank you. I got also an error when I tried to save a manually created
contact after I subscribed it to a mailing list ... So first save worked
OK, next I subscribed to a list in the second tab. When I try to save again
I get a friendly error message : Couldn’t save contact.

Looking in the web.log error found following error:

2020-03-19 19:59:22
[-][1][-][info][craft\services\Elements::_saveElementInternal] Element not
saved due to validation error: Array
2020-03-19 19:59:23 [-][1][-][info][yii\db\Command::query] SELECT "id",
"description", "progress", "progressLabel", "timeUpdated", "fail", "error"
2020-03-19 19:59:23 [-][1][-][profile begin][yii\db\Command::query] SELECT
"id", "description", "progress", "progressLabel", "timeUpdated", "fail",
"error"
2020-03-19 19:59:23 [-][1][-][profile end][yii\db\Command::query] SELECT
"id", "description", "progress", "progressLabel", "timeUpdated", "fail",
"error"
FROM "deprecationerrors"
FROM "deprecationerrors"
FROM "deprecationerrors"
2020-03-19 19:59:23 [-][1][-][profile begin][Twig template] render
template: _includes/forms/errorList
2020-03-19 19:59:23 [-][1][-][profile end][Twig template] render template:
_includes/forms/errorList
2020-03-19 19:59:23 [-][1][-][profile begin][Twig template] render
template: _includes/forms/errorList
2020-03-19 19:59:23 [-][1][-][profile end][Twig template] render template:
_includes/forms/errorList
        'error' => 1
    'error' => 'Couldn’t save contact.'

**Comment by bencroker** [comment]
Fixed the Postgres integrity constraint violations in https://github.com/putyourlightson/craft-campaign/commit/efd81bccb9e6f713eb623c7b208cbecd04c2d4a0.

Regarding the contact not saving, sounds like it might be a missing required field?

**Comment by bartroelands** [comment]
Hi,

Still get DB error :

Integrity constraint violation – yii\db\IntegrityException
<http://www.yiiframework.com/doc-2.0/yii-db-integrityexception.html>SQLSTATE[23502]:
Not null violation: 7 ERROR: null value in column "id" violates not-null
constraint
DETAIL: Failing row contains (null, null, null, 2, 1, 1409, email, [], 0,
0, 0, null, 2020-03-19 19:40:07, 2020-03-19 19:40:07,
0f0654a5-cbd7-4933-a7dc-16e69f27c4e6).
The SQL being executed was: INSERT INTO "campaign_imports" ("id",
"fileName", "filePath", "userGroupId", "userId", "emailFieldIndex",
"fieldIndexes", "mailingListId", "added", "updated", "fails",
"dateImported", "dateCreated", "dateUpdated", "uid") VALUES (NULL, NULL,
NULL, 2, 1, 'email', '[]', 1409, 0, 0, 0, NULL, '2020-03-19 19:40:07',
'2020-03-19 19:40:07', '0f0654a5-cbd7-4933-a7dc-16e69f27c4e6') RETURNING
"id"

Error Info: Array
(
    [0] => 23502
    [1] => 7
    [2] => ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, null, null, 2, 1, 1409, email,
[], 0, 0, 0, null, 2020-03-19 19:40:07, 2020-03-19 19:40:07,
0f0654a5-cbd7-4933-a7dc-16e69f27c4e6).
)

↵Caused by: PDOExceptionSQLSTATE[23502]: Not null violation: 7 ERROR: null
value in column "id" violates not-null constraint
DETAIL: Failing row contains (null, null, null, 2, 1, 1409, email, [], 0,
0, 0, null, 2020-03-19 19:40:07, 2020-03-19 19:40:07,
0f0654a5-cbd7-4933-a7dc-16e69f27c4e6).

in
/Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php
at
line 1290

**Comment by bartroelands** [comment]
I see only one require field email and that has a value :

[image: image.png]

**Comment by bencroker** [comment]
Ok, Postgres is being really problematic. Fixed in https://github.com/putyourlightson/craft-campaign/commit/f97772a46274bdff7ce6c49175b2e055a1617777 and submitted the PR https://github.com/craftcms/cms/pull/5814 to have Craft resolve this in the core.

Please create a new issue for the contact issue as it appears to be unrelated to Postgres.

**Comment by bartroelands** [comment]
ok,

import works now, will create new issue for contact save

br/Bart

**Comment by bencroker** [comment]
Glad to hear it!
