### ISSUE TITLE
CORS problem with Live Preview on multisites

### ISSUE THREAD

**Issue by martinhellwagner** [putyourlightson/craft-campaign#194]
### Describe the bug
When we want to check a Live Preview of a campaign on a Craft multisite, we're getting the CORS problem described in the screenshot below.

### To reproduce
Steps to reproduce the behaviour:
1. Go on a campaign created on a multisite
2. Click the "Preview" button
3. Check the Dev Tools for the error

### Expected behaviour
The Live Preview also works on Craft multisites.

### Screenshots
![9c8302e8-41ff-4fcb-9e2b-b689c603f5a7](https://user-images.githubusercontent.com/19146752/97998697-b9b2fd00-1dea-11eb-8ea2-c3d9cd19c72f.png)

### Versions
- Plugin version: 1.14.2
- Craft version: 3.4.19.1

**Comment by martinhellwagner** [comment]
I've been able to solve the problem by setting the URL of the primary site as the Preview URL. I've changed line 124 of the Campaigns Controller from `'previewUrl' => $campaign->getUrl()` to `'previewUrl' => Craft::$app->getSites()->getPrimarySite()->baseUrl` in order to get it working.

Might that be an acceptable solution to the problem?

**Comment by bencroker** [comment]
It looks like the `LivePreviewController` adds CORS headers:
https://github.com/craftcms/cms/blob/3.4.19.1/src/controllers/LivePreviewController.php#L105-L109

But the `PreviewController` (which the Campaign plugin uses) does not. Does adding the following code to this line solve it for you?
https://github.com/craftcms/cms/blob/3.4.19.1/src/controllers/PreviewController.php#L134

```php
        // Add CORS headers
        Craft::$app->getResponse()->getHeaders()
            ->add('Access-Control-Allow-Origin', '*')
            ->add('Access-Control-Allow-Credentials', 'true')
            ->add('Access-Control-Allow-Headers', 'X-Craft-Token');
```

**Comment by martinhellwagner** [comment]
No, unfortunately that doesn't solve the problem – although I'm guessing it should? 🤔 

Apparently there's no parameter `X-Craft-Token` sent with the request, but even without this header, it doesn't work. I've also tried using `set` instead of `add`, but to no avail.

**Comment by bencroker** [comment]
What about using `setDefault` as in the latest version?
https://github.com/craftcms/cms/blob/3.5.15/src/controllers/LivePreviewController.php#L105-L109

**Comment by martinhellwagner** [comment]
Unfortunately, that doesn't work either. I've updated the CORS header code in the Preview Controller like this:

```
        // Prevent the browser from caching the response
        Craft::$app->getResponse()->getHeaders()
            ->setDefault('Cache-Control', 'no-cache, no-store, must-revalidate')
            ->setDefault('Pragma', 'no-cache')
            ->setDefault('Expires', '0')
            ->setDefault('Access-Control-Allow-Origin', '*')
            ->setDefault('Access-Control-Allow-Credentials', 'true');
    
        if (Craft::$app->getRequest()->getIsOptions()) {
            // This is just a preflight request, no need to route to the real controller action yet.
            return '';
        }
```

Somehow, these headers doesn't get set on the response correctly.

**Comment by bencroker** [comment]
That's strange, it works for me. What is `Access-Control-Allow-Origin` set to in the response header? Perhaps you are overriding it somewhere else?

![Screenshot 2020-11-04 at 10 49 34](https://user-images.githubusercontent.com/57572400/98096131-a6a43980-1e8b-11eb-8022-6a8bbeeb1bd8.png)

**Comment by martinhellwagner** [comment]
Weirdly, I'm getting no Access Control Headers at all in my response. Or am I missing something?

**Comment by bencroker** [comment]
It looks like you need to allow the response to be returned, which will contain the response headers. If you are returning a blank string in the controller then it won't work.

**Comment by martinhellwagner** [comment]
Are you talking about the preflight request? I've actually tried returning the full response as well, but that doesn't seem to work either.

```
        if (Craft::$app->getRequest()->getIsOptions()) {
            return Craft::$app->getResponse()->getHeaders()
                ->setDefault('Cache-Control', 'no-cache, no-store, must-revalidate')
                ->setDefault('Pragma', 'no-cache')
                ->setDefault('Expires', '0')
                ->setDefault('Access-Control-Allow-Origin', '*')
                ->setDefault('Access-Control-Allow-Credentials', 'true');
        }
```

**Comment by bencroker** [comment]
You need to allow the response to be returned.

**Comment by martinhellwagner** [comment]
I'm not sure that I follow. How do I do that – do I have to change something in Craft's Preview Controller?

**Comment by bencroker** [comment]
Nothing for you to do, just don't return in your test code.

**Comment by martinhellwagner** [comment]
Still don't follow. I'm not returning the response anywhere? I've reset the Preview Controller and _only_ added these three lines:

```
            ->setDefault('Expires', '0')
            ->setDefault('Access-Control-Allow-Origin', '*')
            ->setDefault('Access-Control-Allow-Credentials', 'true');
```

**Comment by martinhellwagner** [comment]
Everything else is exactly how it came with `composer install`.

**Comment by bencroker** [comment]
Your code should look like this:

```php
        // Prevent the browser from caching the response
        Craft::$app->getResponse()->getHeaders()
            ->set('Cache-Control', 'no-cache, no-store, must-revalidate')
            ->set('Pragma', 'no-cache')
            ->set('Expires', '0');

        // Add CORS headers
        Craft::$app->getResponse()->getHeaders()
            ->set('Access-Control-Allow-Origin', '*')
            ->set('Access-Control-Allow-Credentials', 'true')
            ->set('Access-Control-Allow-Headers', 'X-Craft-Token');

        // Re-route the request, this time ignoring the token
        $urlManager = Craft::$app->getUrlManager();
        $urlManager->checkToken = false;
        $urlManager->setRouteParams([], false);
        $urlManager->setMatchedElement(null);
        return Craft::$app->handleRequest(Craft::$app->getRequest(), true);
```

**Comment by martinhellwagner** [comment]
Yes, that's exactly how it looks. But that doesn't work unfortunately. 🙁 
Still the same error.

**Comment by bencroker** [comment]
What do your response headers look like now?

**Comment by martinhellwagner** [comment]
This is what the request that actually succeeds looks like:

![Screenshot 2020-11-04 at 16 06 56](https://user-images.githubusercontent.com/19146752/98128231-f00a7e00-1eb7-11eb-9683-d982fb13741d.png)

However, the request that fails looks like this:

![Screenshot 2020-11-04 at 16 07 01](https://user-images.githubusercontent.com/19146752/98128192-e3862580-1eb7-11eb-98cc-dff779cef578.png)

**Comment by bencroker** [comment]
The request that fails contains no response. What is the difference between the two?

**Comment by martinhellwagner** [comment]
I'm not really sure why there are actually two requests. All we did was create a campaign and try to preview it. Whatever happens then is sent from the plugin to the Preview Controller, I guess?

**Comment by martinhellwagner** [comment]
When trying to do the _exact same_ thing on the primary site, only one request gets sent and the response contains the correct headers.

Might it be that not the PreviewController is the problem, but the way the request is sent from a campaign on a non-primary site?

**Comment by bencroker** [comment]
A [CORS preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) is sent before the POST request if it is a cross-origin request. But I don't get why it doesn't contain the correct headers.

Does your PreviewController contain this? 
```php
        if (Craft::$app->getRequest()->getIsOptions()) {
            // This is just a preflight request, no need to route to the real controller action yet.
            return '';
        }
```

**Comment by bencroker** [comment]
Do you have the possibility to update Craft and Campaign to the latest versions? I probably should have asked this at the very beginning of this issue ;)

**Comment by martinhellwagner** [comment]
An update of Campaign should be possible, an update of Craft not right now (since our system is fairly complex and an update to 3.5 needs to be carefully executed).

**Comment by bencroker** [comment]
So while testing, I realised that the Campaign plugin uses the `LivePreviewController` after all.

To eliminate the question of whether the plugin or Craft is at fault here, can you please test live previewing a Category (categories also use the `LivePreviewController`) in a non-primary site and see if that works?

**Comment by martinhellwagner** [comment]
Yes, I've realized that Categories use a similarly structured call to the one in Campaign. However, I don't seem to be able to live-preview Categories – am I missing something?

![Screenshot 2020-11-09 at 18 00 16](https://user-images.githubusercontent.com/19146752/98572187-a229b780-22b5-11eb-9bac-672acd1e4ad6.png)

**Comment by bencroker** [comment]
You need to assign a valid template to the category group for the live preview button to appear.

**Comment by martinhellwagner** [comment]
Ah, of course – sorry! 😛 

There's actually the same error appearing when trying to live-preview a category with a valid template on a multisite. So the Live Preview Controller is at fault then?

**Comment by martinhellwagner** [comment]
I see that https://github.com/craftcms/cms/issues/6355 has been added in Craft 3.5 – but that's probably not the solution to the problem, since I've already tried `setDefault` in the Live Preview Controller.

**Comment by bencroker** [comment]
Probably not, but either way this looks like an issue with Craft and not with Campaign. If you can determine that it is an issue with Craft 3.5 then it should be reported there, let me know what you find.

**Comment by martinhellwagner** [comment]
Might be a while until we have the time to upgrade our project to Craft 3.5, but when we do I'll let you know. Thanks for the help so far – much appreciated! 🙏

**Comment by martinhellwagner** [comment]
@bencroker 

We have finally come around to upgrading our Craft CMS – it's at 3.6.7 now. Unfortunately, the problem still persists. Any idea how we can solve this?

**Comment by bencroker** [comment]
As per https://github.com/putyourlightson/craft-campaign/issues/194#issuecomment-723112685, can you please test live previewing a Category in a non-primary site and see if that works? My best guess is that this is an issue in Craft. To work around this, you could manually set an `Access-Control-Allow-Origin` header on the server, to ensure that CORS access is always allowed for your multi-site domains.

**Comment by martinhellwagner** [comment]
I did test that on November 9, and it didn't work. However, I tested again today, and it still doesn't work. So I presume that the `LivePreviewController` has the wrong CORS headers set for multisite previews to work?

**Comment by bencroker** [comment]
Please create an issue in https://github.com/craftcms/cms/issues about this as I see the correct CORS headers added in https://github.com/craftcms/cms/blob/3.6.7/src/controllers/LivePreviewController.php#L105-L109. Feel free to link to this issue for reference.

**Comment by martinhellwagner** [comment]
Actually, the problem lies just in these lines of code: if I'm changing the lines to include the exact source instead of the wildcard in `Access-Control-Allow-Origin` (and do the same in the NGINX config to allow the preflight request), the preview is rendered correctly.

**LivePreviewController.php:**

```
// Add CORS headers
$this->response->getHeaders()
    ->setDefault('Access-Control-Allow-Origin', 'https://our-base-domain.com')
    ->setDefault('Access-Control-Allow-Credentials', 'true')
    ->setDefault('Access-Control-Allow-Headers', 'X-Craft-Token');
```

**NGINX Config:**

```
if ($request_method = OPTIONS) { 
    add_header Access-Control-Allow-Origin "https://our-base-domain.com";
    add_header Access-Control-Allow-Credentials "true";
    add_header Access-Control-Allow-Headers "X-Craft-Token";
    return 200; 
}
```

With the standard headers in the Live Preview Controller, I'm getting the following error:

```
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*'
when the request's credentials mode is 'include'. The credentials mode of requests initiated by
the XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by martinhellwagner** [comment]
I've opened an issue in the Craft CMS repo. 🙂

**Comment by bencroker** [comment]
This is finally fixed in version 1.21.0.

**Comment by martinhellwagner** [comment]
@bencroker 

Is this really fixed? 🤔 

I'm still getting the same error on version 1.21.0 (with Craft 3.7.13):

![Screenshot 2021-09-22 at 15 46 41](https://user-images.githubusercontent.com/19146752/134355750-18305927-84e8-4694-a106-a61575ef640d.png)

Are there still some special NGINX CORS settings we need to include in our configs?

**Comment by bencroker** [comment]
Have you added the host to the AJAX origins that should be allowed to access live preview? Sorry I haven't had a chance to document this properly yet.
https://github.com/putyourlightson/craft-campaign/blob/9204863d1cf725bcd7e1ea5bf96c3bed3ac2076e/src/config.php#L39-L42

**Comment by martinhellwagner** [comment]
@bencroker 

Just did now, but it didn't seem to help. Is there something I'm missing? These are the contents of our `config/campaign.php` file:

```
<?php

return [
    // Live (production) environment
    'live' => [
        // The AJAX origins that should be allowed to access live preview
        'allowedOrigins' => [
            'https://www.bistum-passau.de',
        ],
    ],

    // Staging environment
    'staging' => [
        // The AJAX origins that should be allowed to access live preview
        'allowedOrigins' => [
            'https://stage.bistum.fredmansky.com',
        ],
    ],

    // Local environment
    'local' => [
    ],
];
```

**Comment by bencroker** [comment]
Hmm, it's working for me. What error message are you now getting in the console?

**Comment by martinhellwagner** [comment]
It's actually the same error message as before. Did you change anything in your NGINX Config?

**Comment by bencroker** [comment]
No, it shouldn't be necessary to change the NGINX config for this to work.

**Comment by martinhellwagner** [comment]
@bencroker 

Turns out the problem is (still) the wildcard `*` in the following commit: https://github.com/craftcms/cms/commit/a9e07bf9d1eb65c1fd9f6c1ed76ada349a705687

If the base domain (the one from `allowedOrigins`) is used in the Live Preview Controller instead of the wildcard `*`, then preview across subdomains works fine.

We're now on Craft 3.7.13 and Campaign 1.21.0 – the newest versions.

**Comment by bencroker** [comment]
> If the base domain (the one from allowedOrigins) is used in the Live Preview Controller instead of the wildcard *, then preview across subdomains works fine.

Correct, and this is what the Campaign plugin now does:
https://github.com/putyourlightson/craft-campaign/blob/9204863d1cf725bcd7e1ea5bf96c3bed3ac2076e/src/Campaign.php#L666

Which should happen _before_ Craft sets the default to the wildcard:
https://github.com/craftcms/cms/blob/6bf5d5f4d5ee70cf70e09776454472d7babda8b6/src/controllers/LivePreviewController.php#L104

Are you sure that the wildcard is not being set somewhere else, perhaps a plugin/module or your Nginx configuration?

**Comment by bencroker** [comment]
Perhaps you could try it with `set` instead of `setDefault` in the Campaign class?

```php
Craft::$app->getResponse()->getHeaders()->set('Access-Control-Allow-Origin', $origin);
```

**Comment by martinhellwagner** [comment]
@bencroker 

I've searched our whole vendor folder for `'Access-Control-Allow-Origin'`, and tried replacing the wildcard on other locations where I've found it. The only location where a change works is the Live Preview Controller.

We also have the following snippet in our NGINX config, but that shouldn't be of relevance to the preview I guess?

```
# Define static file caching and set CORS header
location ~* ^.+\.(?:css|cur|js|jpe?g|gif|htc|ico|png|mp4|html|svg|webp|webm|woff|woff2)$ {
  auth_basic off;
  allow all;
  expires 1y;
  access_log off;
  add_header Cache-Control "public";
  add_header Access-Control-Allow-Origin "*";
  tcp_nodelay off;
  open_file_cache max=3000 inactive=120s;
  open_file_cache_valid 45s;
  open_file_cache_min_uses 2;
  open_file_cache_errors off;

  try_files $uri $uri/ /index.php?$query_string;
}
```

Apart from that, no `'Access-Control-Allow-Origin'` is set to the wildcard anywhere – neither in the code nor in any NGINX config.

**Comment by martinhellwagner** [comment]
I've also tried `set` instead of `setDefault`, but that didn't help either unfortunately.

**Comment by bencroker** [comment]
Hmm, can you add a `dd` after that line to ensure the code is being executed?

```php
Craft::dd(Craft::$app->getResponse()->getHeaders()->get('Access-Control-Allow-Origin'));
```

**Comment by martinhellwagner** [comment]
@bencroker 

The code was indeed not called. I've also found the root cause of the problem – the `config/campaign.php` file needs an "all environments" wildcard itself. Just specifying the separate environments doesn't suffice.

```
<?php

return [
    // All environments
    '*' => [
    ],

    // Live (production) environment
    'live' => [
        // The AJAX origins that should be allowed to access live preview
        'allowedOrigins' => [
            'https://www.bistum-passau.de',
        ],
    ],

    // Staging environment
    'staging' => [
        // The AJAX origins that should be allowed to access live preview
        'allowedOrigins' => [
            'https://stage.bistum.fredmansky.com',
        ],
    ],

    // Local environment
    'local' => [
    ],
];
```

**Comment by bencroker** [comment]
Indeed it does!
